version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_test2111Project
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
- name: PackX
  gitServerName: SIQAPsurGit
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: SIQA_kvv_wm_io
  gitUrl: https://github.webmethods.io/kvv
  gitUsername: kvv
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: siqagituser
  gitUrl: https://github.com/vijetadixit
  gitUsername: siqagituser
  gitBranch: Test
